
server:
  port: 5002
spring:
  application:
    name: TASK-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/tms_task
    username: root
    password: Rahul@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true