server:
  port: 5001
spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/tms_user
    username: root
    password: Rahul@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true